export const homeServices = [
  "Plomero",
  "Electricista",
  "Albañl",
  "Reparador de electrodomesticos",
  "Enchapador",
  "Servicio de telefonía / internet",
  "Servicio de gas estacionario",
  "Servicio de agua potable",
  "Planchado",
  "Limpieza de vidrios",
  "Limpieza de colchones",
  "Aseo en casa",
  "Fumigación de plagas",
  "Lavado de autos",
  "Pintor",
  "Organización de cables",
  "Mudanzas",
];

export const hoursAvaible = [
  "6:00 a.m.",
  "7:00 a.m.",
  "8:00 a.m.",
  "9:00 a.m.",
  "10:00 a.m.",
  "11:00 a.m.",
  "12:00 p.m.",
  "1:00 p.m.",
  "2:00 p.m.",
  "3:00 p.m.",
  "4:00 p.m.",
  "5:00 p.m.",
  "6:00 p.m.",
  "7:00 p.m.",
  "8:00 p.m.",
];

export const daysAvaible = [
  "Lunes",
  "Martes",
  "Miercoles",
  "Jueves",
  "Viernes",
  "Sabado",
  "Domingo",
  "Todos los dias",
];
